backend: 
  name: github
  repo: a-trost/atrostdotcom

media_folder: static/assets
public_folder: /assets

collections: 
  - name: post
    label: Posts
    folder: src/posts
    create: true
    fields: 
      - {name: title, label: Title}
      - {name: date, label: Create At, widget: date }
      - {name: image, label: Image, widget: image}
      - {name: body, label: Post, widget: markdown}

  - name: project
    label: Projects
    folder: src/projects
    create: true
    fields: 
      - {name: title, label: Title}
      - {name: image, label: Image, widget: image}
      - {name: body, label: Details, widget: markdown}

